apiVersion: v1
kind: Service
metadata:
  name: addressbookcluster
  labels:
    service: addressbookcluster
spec:
  selector:
    app: addressbook
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # Container port
    nodePort: 31010 # Host port
    targetPort: 8080
    protocol: TCP
