apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeployment
spec: 
  replicas: 3
  template: 
    metadata:
      labels: 
        app: addressbook
    spec: 
      containers: 
      - name: addressbook-container
        image: dd999/myapp
        ports:
        - containerPort: 8080
